#
# Makefile to compile and link the GTK+ programs
# This makefile was generated by cut-n-paste of the following:
#    gcc -Wall -g program.c  `pkg-config --cflags gtk+-2.0` -o gtk_program `pkg-config --libs gtk+-2.0`
# System changes and updates may necessitate updates to this makefile

GTK_INCLUDE = -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libpng14
GTK_LIB = -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0
CC = gcc -g -Wall

gtk_calculator: gtk_calculator.c
	$(CC) gtk_calculator.c $(GTK_INCLUDE) -o gtk_calculator $(GTK_LIB)

clean:
	rm -f *.o *~ gtk_calculator
